### ISSUE TITLE
Add a "Submit Feedback" button or chatbox on the site

### ISSUE THREAD

**Issue by SaraWolk** [Equal-Vote/star-server#284]
This could be in the bottom left corner in the same place that other sites put a chatbot integration.

**Comment by ArendPeter** [comment]
Youtube's been showing me a lot of marker.io ads recently, seems like a good tool for setting this up

https://www.youtube.com/watch?v=yrWNPGxOIOg

It will let us do the following flow

* Adds Submit Feedback button on the website
* Tool will generate screenshot, and let the user annotate it and provide a description
* A github issue will automatically be generated along with the screenshot and user browser info
* When we close the github issue the user will be notified with an email that their bug has been resolved

**Comment by SaraWolk** [comment]
I was thinking about something similar. We could offer chatbot as a pro
feature for clients only, or in general?
For the IPO election we added FreshDesk to the platform and built out all
the infrastructure to give automated replies to FAQ and all of that. It
costs money, but when you go back to free mode it still saves your whole
account, so it's all there if we want to fire it up again.

I pretty much set up and ran that whole part of it myself (with a couple
volunteers to help) and it worked great. No complaints.

**Comment by SaraWolk** [comment]
The Marker.io video was well done. It looks like a great tool. The
integration with Trello was cool too. I assume you'd rather integrate it
with GitHub directly though? I'm not sure if we'll need it long enough to
justify its use, but maybe. I'm down to try it if you want.

**Comment by mikefranze** [comment]
Quick route would be to either have a mail-to link and have them email us or have them fill out a form and have the server send an email to us.

**Comment by ArendPeter** [comment]
That option would work too, but I feel like we'll get significantly more participation (and clearer bug reports) if we have a easy reporting tool that they can open anywhere on the website, so I'd lean toward using a service. Marker.io looks really good, but I'll try and do more research to see alternatives

For a helpdesk service vs a feedback reporting service, I think we'll want both. Helpdesk is for people who are having trouble with the voting process, and feedback is for people who discover bugs. We could pay for the feedback service during the early stages of the product (the next 3-12 months? depending on how much it's used), and the helpdesk service could be intermittent based on the client?

**Comment by ArendPeter** [comment]
I think we'll need freshdesk for realtime support and some other tool for feedback reporting. These are my comparisons between feedback tracking alternatives

## Marker.io

This specialized tool for adding a feedback button which integrates with your issue tracking tool (for us that's github)

**Pricing**
$39 / month for basic plan, there's no free plan

**Pros**
* **Github Integration**: the github integration means we don't have to think about marker.io after it's setup, so we'll be much more likely to take advantage of it's features
* **Detailed Feedback**: users can annotate a screenshot and  when the issue is reported 
* **Automated Notifications**: users get automatically notified when their issue is resolved
* **Intuitive Feedback**: I tested the feedback flow of marker io and HotJar. They're both good but I think marker io is slightly better

**Cons**
* **Lack of additional features / Analytics**: Marker io is just for bug reporting, no other analytics related features

## Hotjar

This is a very powerful marketing analytics tool, that also has a feedback button included

**Pricing**
Free for up to 20 reports a month, then it's $59/month

**Pros**
 * **Analytics Tools**: This has additional tools like funnel metrics, heat maps, surveys, and user recordings. ([this video](https://youtu.be/C42yuyRpb6I)
 has a good overview)
 * **Intuitive Feedback**: I tested the feedback flow of marker io and HotJar. They're both good but I think marker io is slightly better
 
 **Cons**
* **No github integration**: Without a github integration, we'd need to scroll through hotjar to get the information. This overhead means we're less likely to leverage it's features

## References
Hotjar vs google analytics: https://youtu.be/C42yuyRpb6I
Marker customer interview ad: https://youtu.be/RKt4MyWD9u8?t=157
Session Replay Legality: https://www.bairdholm.com/blog/session-replay-litigation-and-privacy/
Marker io github integration: https://marker.io/github-bug-tracking
Hotjar feedback details: https://www.youtube.com/watch?v=Y-3KI__Ekmc
