### ISSUE TITLE
Option “Explore more settings” - Create a Poll

### ISSUE THREAD

**Issue by masiarek** [Equal-Vote/star-server#479]
![](https://github.com/Equal-Vote/star-server/assets/857777/cf9340f7-7c6e-4bef-9219-627d87032b53)

- Video1: https://youtu.be/n0kRoAztPAw
- Video2: https://youtu.be/1_VT2phlMdY 
- Video2: https://youtu.be/eD5DmXWm5fM

Proposed Solutions - options: 
Link: https://docs.google.com/document/d/1vuG90uZ3vUtnFAbL3iv2ttz7vvLeEA5bGrBRBUQhdwE/edit

**Comment by ArendPeter** [comment]
What if we renamed "Explore more settings", to "Continue editing in advanced mode" or something like that?

Clicking "Explore more settings" is different from "Create Election" since it prepopulates the information you provided to the quick poll, but I agree that it's not clear from the current experience

**Comment by ArendPeter** [comment]
These have been resolved with the new election creation flow
