### ISSUE TITLE
Add "Sign-up" link, add "Try me" link, redesign Home Page

### ISSUE THREAD

**Issue by masiarek** [Equal-Vote/star-server#496]
Add "Sign-up" link - it is missing.

Add "Try me" link with a frictionless experience 
 
As-Is
We have a Quick Poll as our default "demo mode" / "try me" mode :
PROS - easy and quick
CONS - very limiting (unable to control ANY aspects of the Poll - stop it, change title, set end date, etc) 

Do we want to have the Quick Poll feature with limited functionality and has a rigid, inflexible design so prominently visible on our home page? 
Proposal 
- add a link to QuickPoll feature on our home page (instead of having complete Quick Poll interface on the Home Page).
- add a link to a Demo Election (voters are in "test" mode by definition as opposed to "Live" mode that is featured in Quick Poll)

Concerns / open questions:
Right now - the demo mode forces users to Sign-up - but this is *friction* (I would not trust at first any website).
Maybe we can have few test user ids that can be used for test drive (randomly assign assign a Try-me user id).
Each month we refresh / reset / delete the content for all Try-me accounts (as long as we clearly communicate the behavior - it is fine - if I like what I see - I will register to keep my content)

Video: "Sign-up" and "Try me" feedback (compare other voting websites): https://youtu.be/pOkBhyDKp3c
QuickPoll: https://docs.google.com/document/d/1d_p3Nknpk8-AW9axhuNfD6bxnkpWty7pYRuloHDVtKQ/edit
Demo Election - https://docs.google.com/document/d/1IqO6PmEi5fbq7-ZSnmiqhXi_aJoR4BgtpxIYUZCgJYI/edit
Live/Test mode: https://docs.google.com/document/d/1PKkWRbZt5BAr44mSqjvLJSvxNne87iF2KzWe_aqEf-I/edit

**Comment by ArendPeter** [comment]
Interesting, we've always assumed it was a given that the quick poll would be on the front page (since that's what star.vote does), but you're right that's not necessarily a given (for example, strawpoll features "create a poll" prominently, but it doesn't have a widget directly on the front page)

Regarding the test user ids, I don't think that will be necessary. If we want to expose more features without requiring login we can just make those accessible without having a test user login. 

The main feature that must require login is editing past elections, but there's many other features that could potentially be included without requiring login. We just need to have more conversation to figure out where to draw the line
